version: '3'
services:
  mongodb:
    image: mongo:3.4.24-xenial
  hpfeeds-forwarder:
    build:
      context: .
    image: hpfeeds-forwarder:latest
    env_file:
      - hpfeeds-forwarder.env
    links:
      - mongodb:mongodb
